# Generated by Django 5.0.6 on 2026-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://images.pexels.com/photos/7166647/pexels-photo-7166647.jpeg?auto=compress&cs=tinysrgb&w=1200'),
        ),
    ]
