services:
  - type: web
    name: furniture-mart
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_store && python manage.py collectstatic --noinput
    startCommand: gunicorn sarvotam.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
